### ISSUE TITLE
Any way to avoid using username and password?

### ISSUE THREAD

**Issue by paulcpederson** [dolbyzerr/grunt-github-releaser#4]
Would like to avoid having my username and password in plaintext. Not entirely sure what you mean in the doc by:

> Basic authorization, see "Personal Access Tokens" in https://github.com/settings/applications

Can I use a personal access token instead?

**Comment by thanpolas** [comment]
@dolbyzerr can you provide a config setup where a Github Access Token is used vs username / password? I could not set it up no matter how I tried and by looking into the source code I understood that Access Token authentication is not implemented...

Please help

**Comment by dolbyzerr** [comment]
@thanpolas 
You need to generate github personal token (you can do it here https://github.com/settings/tokens), then use it as a password. You can provide it explicitly:
```
...
    'github-release': {
      all: {
        options: {
          repository: 'username/repo',
          auth: {
            user: 'username',
            password: 'your_generated_token'
          }
        },
        files: { ... }
      }
    }
...
```

Or you can store it in ENV variable (like I do), I store it in my `.profile`
```
export GITHUB_TERMINAL="<your_generated_token>"
```
and use it like:
```
...
    'github-release': {
      all: {
        options: {
          repository: 'username/repo',
          auth: {
            user: 'username',
            password: process.env.GITHUB_TERMINAL
          }
        },
        files: { ... }
      }
    }
...
```

**Comment by thanpolas** [comment]
yes, that worked @dolbyzerr thank you! It'd help if it's mentioned in the README like you state here

Thanks for the great work!
